### ISSUE TITLE
Please Review

### ISSUE THREAD

**Issue by ctuong** [ctuong/Yelp#1]
May not have time to work on it this weekend, so I'm submitting it now. Please review /cc @codepathreview Thanks!

**Comment by codepathreview** [comment]
I can't build your project, it says a config.plist is missing

**Comment by ctuong** [comment]
Hi @codepathreview, as per https://github.com/ctuong/Yelp#setup, you'll need a config.plist file with the keys/token/secrets. Should I add that to the repo?

**Comment by codepathreview** [comment]
@ctuong yup please!
Your solution with an external file is elegant, but makes my life more difficult :)
All others just included the keys in their code

**Comment by ctuong** [comment]
@codepathreview sorry about that! Done!

**Comment by codepathreview** [comment]
:+1: nice work. The primary challenge of this homework was to learn how to use UITableView to manage a complex form, establish communication between view controllers, and apply the correct Auto Layout constraints. For each point in the homework feedback checklist, I'll either confirm that you're on the right track with the implementation, or I'll provide some feedback:
- For the restaurant cell, nice work encapsulating the properties into the private class extension.
- Note that you should resolve all the Auto Layout constraint warnings in your nibs. (BusinessCell.xib)
- Nice work linking the filter model with the controls. See this [popular form library](https://github.com/nicklockwood/FXForms) for an alternative to implementing forms manually.
- Nice work connecting the view controllers via the custom filter delegate. This is a popular pattern for handling events between view controllers.

This was a challenging assignment, congrats on completing it successfully!

-- dirk
